#!/bin/sh

set -e

brew install vim --with-override-system-vi
brew install ripgrep fzf

path="$HOME/.simsalavim"

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

ln -sf $path/vimrc ~/.vimrc

vim - +PlugUpgrade +PlugInstall +PlugUpdate +PlugClean +qall
