#!/bin/sh

set -e

SIMSALAVIM_PATH="$HOME/.simsalavim"

if [ -e $SIMSALAVIM_PATH/.git ]; then
	cd $SIMSALAVIM_PATH && git pull
else
	git clone https://github.com/filippoliverani/simsalavim.git $path
fi

brew install nvim lazygit ripgrep fd

ln -sf $SIMSALAVIM_PATH/nvim ~/.config/nvim
